### ISSUE TITLE
ECONNRESET in Docker healthcheck

### ISSUE THREAD

**Issue by thewilkybarkid** [hypermedia-app/generic.hypermedia.app#51]
We're [using a healthcheck](https://github.com/libero/article-store/blob/5758e15e23b5023f583f2b6d7d9bfa7727c0c17b/.docker/docker-compose.yml#L16-L19) the same as added in https://github.com/hypermedia-app/generic.hypermedia.app/pull/50, but running https://github.com/libero/article-store locally I'm seeing a lot of:

```
console_1  | 3:01:30 PM: Middleware error
console_1  | Error: read ECONNRESET
console_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
```

and

```
console_1  | 3:01:15 PM: Middleware error
console_1  | Error: write ECONNRESET
console_1  |     at afterWriteDispatched (internal/stream_base_commons.js:150:25)
console_1  |     at writeGeneric (internal/stream_base_commons.js:141:3)
console_1  |     at Socket._writeGeneric (net.js:771:11)
console_1  |     at Socket._write (net.js:783:8)
console_1  |     at doWrite (_stream_writable.js:431:12)
console_1  |     at clearBuffer (_stream_writable.js:551:7)
console_1  |     at Socket.Writable.uncork (_stream_writable.js:325:7)
console_1  |     at connectionCorkNT (_http_outgoing.js:656:8)
console_1  |     at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

This might explain https://github.com/libero/article-store/pull/166#issuecomment-572601976.

/cc @giorgiosironi

**Comment by tpluscode** [comment]
I don't know where it comes from. Saw it once but failed to repeat 🤔

Is this only happening locally you say?

**Comment by thewilkybarkid** [comment]
Saw it again yesterday, but tried this morning to see if I could debug and nothing. 😅

Will do it next time I see it.

**Comment by thewilkybarkid** [comment]
Wonder if this is https://github.com/nodejs/node/issues/27916.
